import esbuild from 'esbuild'
import process from 'process'
import fs from 'fs'
import path from 'path'
import {builtinModules} from 'node:module'
import sveltePlugin from 'esbuild-svelte'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

// Dev builds land in the dev vault, never in Sean's live vault.
// Production deploys to the live vault go through `npm run deploy:prod`.
const devPluginDir =
  process.env.DTP_DEV_PLUGIN_DIR ??
  path.resolve('../daily-task-panel-demo-vault/.obsidian/plugins/daily-task-panel')

const options = {
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: ['obsidian', ...builtinModules, ...builtinModules.map((m) => `node:${m}`)],
  format: 'cjs',
  target: 'es2022',
  logLevel: 'info',
  // Production ships minified: the Svelte 5 runtime alone is 164 kB unminified, 56 kB minified.
  minify: prod,
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  plugins: [
    sveltePlugin({
      compilerOptions: {css: 'injected'},
    }),
  ],
  outfile: prod ? 'main.js' : path.join(devPluginDir, 'main.js'),
}

if (prod) {
  await esbuild.build(options).catch(() => process.exit(1))
} else {
  fs.mkdirSync(devPluginDir, {recursive: true})
  // .hotreload makes the Hot Reload plugin pick up rebuilds automatically
  fs.writeFileSync(path.join(devPluginDir, '.hotreload'), '')
  const syncStatic = () => {
    for (const file of ['manifest.json', 'styles.css']) {
      fs.copyFileSync(file, path.join(devPluginDir, file))
    }
  }
  syncStatic()
  for (const file of ['manifest.json', 'styles.css']) {
    fs.watchFile(file, {interval: 500}, syncStatic)
  }
  console.log(`dev build → ${devPluginDir}`)
  const ctx = await esbuild.context(options)
  await ctx.watch()
}
